package seeder

import "github.com/aldiramdan/go-backend/databases/orm/models"

var VehicleSeed = models.Vehicles{
	{
		Name:        "Van",
		Location:    "Yogyakarta",
		Description: "short description",
		Price:       450000,
		Status:      "Available",
		Stock:       10,
		CategoryID:  1,
		Picture:     "image/cars",
		Rating:      0,
		TotalRent:   0,
	},
	{
		Name:        "Lamoborghini",
		Location:    "South Jakarta",
		Description: "short description",
		Price:       12450000,
		Status:      "Available",
		Stock:       10,
		CategoryID:  1,
		Picture:     "image/cars",
		Rating:      0,
		TotalRent:   0,
	},
	{
		Name:        "Jeep",
		Location:    "Malang",
		Description: "short description",
		Price:       450000,
		Status:      "Available",
		Stock:       10,
		CategoryID:  1,
		Picture:     "image/cars",
		Rating:      0,
		TotalRent:   0,
	},
	{
		Name:        "White Jeep",
		Location:    "Kalimantan",
		Description: "short description",
		Price:       450000,
		Status:      "Available",
		Stock:       10,
		CategoryID:  1,
		Picture:     "image/cars",
		Rating:      0,
		TotalRent:   0,
	},
	{
		Name:        "Vespa",
		Location:    "Yogyakarta",
		Description: "short description",
		Price:       450000,
		Status:      "Available",
		Stock:       10,
		CategoryID:  2,
		Picture:     "image/motorbike",
		Rating:      0,
		TotalRent:   0,
	},
	{
		Name:        "Honda KLX",
		Location:    "Kalimantan",
		Description: "short description",
		Price:       550000,
		Status:      "Available",
		Stock:       10,
		CategoryID:  2,
		Picture:     "image/motorbike",
		Rating:      0,
		TotalRent:   0,
	},
	{
		Name:        "Honda",
		Location:    "Malang",
		Description: "short description",
		Price:       450000,
		Status:      "Available",
		Stock:       10,
		CategoryID:  2,
		Picture:     "image/motorbike",
		Rating:      0,
		TotalRent:   0,
	},
	{
		Name:        "Matic Bike",
		Location:    "Yogyakarta",
		Description: "short description",
		Price:       450000,
		Status:      "Available",
		Stock:       10,
		CategoryID:  2,
		Picture:     "image/motorbike",
		Rating:      0,
		TotalRent:   0,
	},
	{
		Name:        "Matic Bike",
		Location:    "Yogyakarta",
		Description: "short description",
		Price:       450000,
		Status:      "Available",
		Stock:       10,
		CategoryID:  2,
		Picture:     "image/motorbike",
		Rating:      0,
		TotalRent:   0,
	},
	{
		Name:        "Fixie",
		Location:    "Yogyakarta",
		Description: "short description",
		Price:       250000,
		Status:      "Available",
		Stock:       10,
		CategoryID:  3,
		Picture:     "image/bike",
		Rating:      0,
		TotalRent:   0,
	},
	{
		Name:        "Sport Bike",
		Location:    "Kalimantan",
		Description: "short description",
		Price:       250000,
		Status:      "Available",
		Stock:       10,
		CategoryID:  3,
		Picture:     "image/bike",
		Rating:      0,
		TotalRent:   0,
	},
	{
		Name:        "Onthel",
		Location:    "Malang",
		Description: "short description",
		Price:       250000,
		Status:      "Available",
		Stock:       10,
		CategoryID:  3,
		Picture:     "image/bike",
		Rating:      0,
		TotalRent:   0,
	},
	{
		Name:        "Fixie Gray",
		Location:    "Yogyakarta",
		Description: "short description",
		Price:       250000,
		Status:      "Available",
		Stock:       10,
		CategoryID:  3,
		Picture:     "image/bike",
		Rating:      0,
		TotalRent:   0,
	},
}
